apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: songs
resources:
  - ../../base
patchesStrategicMerge:
  - patch-resources.yaml
configMapGenerator:
  - name: songs-config
    literals:
      - LOG_LEVEL=info
images:
  - name: nginx
    newTag: "1.25"
