apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
namePrefix: songs-
commonLabels:
  app.kubernetes.io/part-of: songs-api
images:
  - name: nginx
    newTag: "1.25"
