apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patch-replicas.yaml
configMapGenerator:
  - name: songs-config
    literals:
      - LOG_LEVEL=debug
